---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Inhalte
- type: directory
  path: exampleSite/content/german/staffelmitglied
  label: Staffelmitglied
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: exampleSite/content/german/blog
  label: Blogeinträge
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: exampleSite/content/german/mitgliederbereich/**/*
  label: Mitgliederbereich
  create: documents
  match: "**/*"
  new_doc_ext: ".md"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite/data
  label: Homepage
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/i18n
  label: Übersetzungen
  create: documents
  match: "**/*"
- type: directory
  path: exampleSite
  label: Konfiguration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/assets/images
public_path: "/images/blog"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
